apiVersion: apps/v1
kind: Deployment
metadata:
  name: qmobile-demo-||env||
  namespace: "||namespace||"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qmobile-demo-||env||
  template:
    metadata:
      labels:
        app: qmobile-demo-||env||
        logging: enabled
    spec:
      terminationGracePeriodSeconds: 100
      containers:
      - image: '||registry||/qmobile_dpc_demo:||version||'
        name: qmobile-demo
        env:
        - name: NGINX_SERVER_NAME
          value: default
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /etc/localtime
          name: tz-config
        - name: configmap-volume
          mountPath: /app/env.js
          subPath: env.js          
        resources:
          limits:
            memory: "32Mi"
          requests:
            memory: "16Mi"
      volumes:
      - name: configmap-volume
        configMap:
          name: qmobile-demo-config
          items:
            - key: env.js
              path: env.js
      - hostPath:
          path: /usr/share/zoneinfo/Europe/Moscow
          type: ""
        name: tz-config
---
apiVersion: v1
kind: Service
metadata:
  name: qmobile-demo-||env||
  namespace: "||namespace||"
spec:
  ports:
  - port: 80
    name: qmobile-demo
    targetPort: 3000
  selector:
    app: qmobile-demo-||env||
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qmobile-demo-||env||
  namespace: "||namespace||"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
spec:
  rules:
  - host: "||host||"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qmobile-demo-||env||
            port: 
              number: 80
